# Development configuration (comment for Production)
limit_posts: 20
host: 0.0.0.0
future: false
profile: true
#url: "http://localhost:4000"
url: "https://borisschapira.com"
environment: "development"

