[build]
  command = "bundle exec rake build:generate[prod]; npm run lambda:build"
  publish = "_site"
  functions = "lambda"

[context.branch-deploy]
  command = "bundle exec rake build:generate[integ]; npm run lambda:build"

[dev]
  command = "bundle exec rake"
  port = 10443
  publish = "_site"

[[plugins]]
package = "netlify-build-plugin-dareboost"
  [plugins.inputs]
  monitoringIds = "7134"
